---
- name:  Add bitnami repository
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"

- name: Deploy postgres
  kubernetes.core.helm:
    name: my-release
    chart_ref: bitnami/postgresql
    release_namespace: postgresql
    create_namespace: true